Repository boostcampwm-2021/android03-Contact, pull requests merged in 2021-11, with the labels that each got.

#17 일정 리스트 레이아웃 및 어댑터 추가
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/drawable/bg_plan_list_item.xml
  app/src/main/res/layout/item_plan_list.xml
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
Labels: feature

#18 일정 리스트 sticky header 구현
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListHeaderItemDecoration.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/res/layout/item_plan_list.xml
  app/src/main/res/layout/item_plan_list_header.xml
Labels: feature

#19 Feat/#4 search button
  app/src/main/java/com/ivyclub/contact/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendItemData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/util/BaseFragment.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/color/main_bnv_item_color.xml
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/drawable/ic_baseline_clear_24.xml
  app/src/main/res/drawable/ic_baseline_perm_contact_calendar_24.xml
  app/src/main/res/drawable/ic_baseline_person_24.xml
  app/src/main/res/drawable/ic_baseline_search_24.xml
  app/src/main/res/drawable/ic_baseline_settings_24.xml
  app/src/main/res/drawable/shape_search_friend_list_edit_text.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/item_friend_profile.xml
  app/src/main/res/menu/menu_friend_and_group.xml
  app/src/main/res/menu/menu_main_nav.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#21 최근 약속으로 자동 스크롤 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/res/layout/item_plan_list.xml
  app/src/main/res/layout/item_plan_list_header.xml
Labels: 🗓️ 일정 기능, feature

#22 일정 리스트 아이템 클릭 콜백 추가 및 적용
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
Labels: 🗓️ 일정 기능, feature

#23 일정 리스트 아이템 UI 수정
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/res/drawable/bg_plan_list_item.xml
  app/src/main/res/layout/item_plan_list.xml
Labels: 🗓️ 일정 기능, feature

#24 지인 검색 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/item_plan_list_header.xml
Labels: feature, fix

#25 Feat/#3 notification time
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/ui/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/ContactAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  app/src/main/res/anim/button_down.xml
  app/src/main/res/anim/page_fade_in.xml
  app/src/main/res/anim/page_fade_out.xml
  app/src/main/res/anim/recyclerview_fade_in.xml
  app/src/main/res/anim/text_gone.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_add_contact.xml
  app/src/main/res/layout/fragment_notification_time.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/navigation/onboarding_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/DatabaseModule.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/RepositoryModule.kt
  data/src/main/java/com/ivyclub/data/RoomConverters.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
  data/src/main/java/com/ivyclub/data/repository/PersonDao.kt
  data/src/main/java/com/ivyclub/data/repository/PersonDataBase.kt
Labels: feature

#27 일정 리스트 코드 리팩토링
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListItemViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/layout/item_plan_list.xml
  app/src/main/res/layout/item_plan_list_header.xml
  app/src/main/res/values/strings.xml
Labels: 🗓️ 일정 기능, refactor

#28 Feature/#10 plus button click
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/res/layout/dialog_friend.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 👩‍👩‍👧‍👦 지인 리스트 기능, feature

#29 온보딩 뒤로가기 버튼 및 건너뛰기 버튼
  README.md
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/ContactAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/SkipDialog.kt
  app/src/main/res/anim/button_down.xml
  app/src/main/res/layout/fragment_add_contact.xml
  app/src/main/res/layout/fragment_notification_time.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/menu/menu_on_boarding.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/DatabaseModule.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDatabase.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: ✈️ 온보딩 기능, feature

#31 약속 화면 초기 구현
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/navigation/main_nav_graph.xml
Labels: 🗓️ 일정 기능, feature

#48 그룹 추가 기능
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/dialog_friend.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDatabase.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 👩‍👩‍👧‍👦 지인 리스트 기능, feature

#49 약속 상세 정보 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListItemViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/RoomConverters.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDatabase.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, feature

#47 Refactor/#36 on boarding fix
  app/src/main/java/com/ivyclub/contact/ui/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/ContactAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/ContactListManager.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: ✈️ 온보딩 기능, fix

#53 지인 추가/수정 화면 - 기본 정보 입력
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendViewModel.kt
  app/src/main/res/drawable/bg_add_friend_group.xml
  app/src/main/res/drawable/bg_add_friend_group_pop_up.xml
  app/src/main/res/drawable/bg_add_friend_info.xml
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/ic_baseline_check_24.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/values/strings.xml
Labels: feature, ✏️ 지인 추가/수정 기능

#54 그룹화하여 보여주는 기능, 그룹 접는 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendItemData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListViewType.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
  app/src/main/res/layout/item_friend_profile.xml
  app/src/main/res/layout/item_group_divider.xml
  app/src/main/res/layout/item_group_name.xml
  app/src/main/res/values/strings.xml
Labels: feature

#55 돋보기 버튼 클릭 시 포커스 및 키보드 활성화
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
Labels: enhancement

#57 약속 추가/수정 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/FriendAutoCompleteAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/layout/item_friend_auto_complete.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 태훈, 🗓️ 일정 기능, feature

#58 Feat/#41 friend detail
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/anim/star_animation.xml
  app/src/main/res/drawable/bg_plan.xml
  app/src/main/res/drawable/button_favorite.xml
  app/src/main/res/drawable/ic_baseline_build_24.xml
  app/src/main/res/drawable/ic_baseline_call_24.xml
  app/src/main/res/drawable/ic_baseline_favorite.xml
  app/src/main/res/drawable/ic_baseline_not_favorite.xml
  app/src/main/res/drawable/ic_baseline_pen.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: feature, 🕵️ 지인 상세 기능

#61 Refactor/#60 database fix
  app/src/main/java/com/ivyclub/contact/model/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/model/PhoneContactData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListViewType.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/item_friend_profile.xml
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
Labels: fix

#63 지인 추가/수정 화면 정보 저장 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/ExtraInfoListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/FriendExtraInfoData.kt
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 성희, feature, ✏️ 지인 추가/수정 기능

#65 [FIX] #52 - 온보딩 스킵 시 상태 저장
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
Labels: 우진, ✈️ 온보딩 기능, fix

#67 약속 추가/수정 화면 Dialog 기능 구현 및 db 연동
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/FriendAutoCompleteAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListItemViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/SingleLiveEvent.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/item_friend_auto_complete.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, feature

#68 지인 수정 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/AddFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_friend/ExtraInfoListAdapter.kt
  app/src/main/res/navigation/main_nav_graph.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, feature, ✏️ 지인 추가/수정 기능

#69 [FEAT] #66 - 전체 선택기능 추가
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/ContactAdapter.kt
  app/src/main/res/menu/menu_on_boarding_add.xml
  app/src/main/res/values/strings.xml
Labels: 우진, ✈️ 온보딩 기능, feature

#71 지인 추가/수정 화면에서 추가 정보 삭제 기능 구현
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/ExtraInfoListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/FriendExtraInfoData.kt
  app/src/main/res/drawable/bg_add_edit_friend_group.xml
  app/src/main/res/drawable/bg_add_edit_friend_group_pop_up.xml
  app/src/main/res/drawable/bg_add_edit_friend_info.xml
  app/src/main/res/drawable/ic_baseline_remove_24.xml
  app/src/main/res/layout/fragment_add_edit_friend.xml
  app/src/main/res/layout/item_add_friend_extra_info.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 성희, feature, ✏️ 지인 추가/수정 기능

#72 지인 클릭, 롱클릭 이벤트 구현
  app/src/main/java/com/ivyclub/contact/model/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/layout/fragment_select_group_dialog.xml
  app/src/main/res/layout/item_friend_profile.xml
  app/src/main/res/menu/menu_friend_and_group.xml
  app/src/main/res/menu/menu_set_friends_at_friendlist.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: feature

#78 약속 추가/수정 화면 기능 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupFragment.kt
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_select_group_dialog.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, feature

#79 약속 상세정보 화면 삭제 기능 추가
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan_details.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, feature

#80 생년월일 DatePicker로 입력받도록 구현 및 디자인 변경
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/res/drawable/bg_add_edit_friend_group.xml
  app/src/main/res/drawable/bg_add_edit_friend_group_pop_up.xml
  app/src/main/res/drawable/bg_add_edit_friend_info.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/ic_baseline_calendar_today_24.xml
  app/src/main/res/layout/fragment_add_edit_friend.xml
  app/src/main/res/values/strings.xml
Labels: 성희, ✏️ 친구 추가/수정 기능

#81 Feat/#45 friends plan
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/drawable/bg_details.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 우진, feature, 🕵️ 친구 상세 기능

#82 친구 리스트 롱클릭 UX 개선
  app/src/main/java/com/ivyclub/contact/model/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
  app/src/main/res/layout/fragment_friend.xml
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 친구 리스트 기능

#84 [FEAT] #83 - 기본 그룹 생성
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
Labels: ✈️ 온보딩 기능, feature

#90 메뉴 아이템 클릭 처리 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
Labels: 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, fix

#88 [FIX] 지인 텍스트로 추가 시 중복 체크
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
Labels: 태훈, 🗓️ 일정 기능, fix

#89 [FIX] #86 - 생일 입력 시 안뜨는 현상 수정
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
Labels: bug, 우진, fix, 🕵️ 지인 상세 기능

#95 [FIX] #94 - 설정 클릭 시 튕기는 오류 수정
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
Labels: bug, fix

#97 툴바 메뉴 제대로 안뜨는 문제 해결
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
Labels: 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, fix

#101 week3 구현 리팩토링
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/AddGroupDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/AddGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListHeaderItemDecoration.kt
  app/src/main/res/layout/dialog_friend.xml
  app/src/main/res/layout/fragment_add_edit_friend.xml
Labels: 성희

#112 Refactor/#111 edit dao repo
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/AddGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, 원중, 태훈, 우진, refactor

#99 recreate() 로직 변경
  app/src/main/java/com/ivyclub/contact/ui/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/AddGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/dialog_friend.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능

#113 Feat/#102 friend all plan
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendAllPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendAllPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/layout/fragment_friend_all_plan.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/navigation/main_nav_graph.xml
Labels: 우진, feature, 🕵️ 지인 상세 기능

#114 비밀번호 설정 화면 구현
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityFragment.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/layout/fragment_security.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, feature, 🔑 보안 기능

#115 친구 리스트의 버그들 제거
  app/src/main/java/com/ivyclub/contact/model/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
  app/src/main/res/layout/fragment_friend.xml
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, fix

#119 약속 알림 Notification 기능 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/MainApplication.kt
  app/src/main/java/com/ivyclub/contact/service/PlanReminderNotification.kt
  app/src/main/java/com/ivyclub/contact/service/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/service/WorkManagerModule.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, feature, ❗ 알림 기능

#120 즐겨찾기, 친구 그룹 순서에 맞게 추가
  app/src/main/java/com/ivyclub/contact/model/FriendListData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능

#122 [FEAT] #33-사진 추가 기능 및 사진 확대해서 보기
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/ImageDetailFragment.kt
  app/src/main/res/layout/fragment_add_edit_friend.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/layout/fragment_image_detail.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ImageManager.kt
Labels: 우진, feature, ✏️ 지인 추가/수정 기능

#123 비밀번호 분류 화면 구현
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityViewModel.kt
  app/src/main/res/layout/fragment_security.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, 🔑 보안 기능

#128 [FEAT] #126 - 친구 리스트 사진 기능
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/ImageDetailFragment.kt
  app/src/main/res/drawable/photo.jpg
  app/src/main/res/drawable/photo.png
  app/src/main/res/drawable/round_image.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/layout/fragment_image_detail.xml
  app/src/main/res/layout/item_friend_profile.xml
Labels: 우진, 👩‍👩‍👧‍👦 지인 리스트 기능, feature

#130 약속 있는 날 아침, 밤 알림 구현
  app/src/main/java/com/ivyclub/contact/service/PlanReminderNotification.kt
  app/src/main/java/com/ivyclub/contact/service/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/DateUtil.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, feature, ❗ 알림 기능

#131 연락처가 많은 경우 다 가져와지지 않는 버그 해결
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/dialog/DialogGetContactsLoadingFragment.kt
  app/src/main/res/layout/fragment_dialog_get_contacts_loading.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, 원중, ✈️ 온보딩 기능

#132 비밀번호 확인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordActivity.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/layout/fragment_security.xml
  app/src/main/res/navigation/password_nav_graph.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, feature, 🔑 보안 기능

#133 일정 리스트 화면 Flow 적용
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, refactor

#134 [FEAT] #129 - 위젯 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/util/MyRemoteViewsFactory.kt
  app/src/main/java/com/ivyclub/contact/util/MyRemoteViewsService.kt
  app/src/main/java/com/ivyclub/contact/util/WidgetProvider.kt
  app/src/main/res/layout/item_widget.xml
  app/src/main/res/layout/widget.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/widget_provider.xml
Labels: 우진, 🗓️ 일정 기능, feature

#127 설정화면 틀 제작 및 알림 시간 조정 구현
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
  app/src/main/res/drawable/ic_baseline_import_contacts_24.xml
  app/src/main/res/drawable/ic_baseline_notifications_24.xml
  app/src/main/res/drawable/ic_baseline_security_24.xml
  app/src/main/res/layout/fragment_dialog_notification_time.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/MyPreference.kt
Labels: 원중, ⚙️설정화면

#136 Fix/위젯 기능 빌드 실패 관련 수정
  app/src/main/java/com/ivyclub/contact/util/MyRemoteViewsFactory.kt
  app/src/main/java/com/ivyclub/contact/util/WidgetProvider.kt
  app/src/main/res/layout/widget.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, fix

#138 설정화면과 보안화면 연결 및 설정화면 BottomNavigationView invisible
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordFragment.kt
  app/src/main/res/navigation/main_nav_graph.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature

#139 애플리케이션 아이콘 추가
  app/src/main/AndroidManifest.xml
  app/src/main/ic_contact_launcher-playstore.png
  app/src/main/java/com/ivyclub/contact/service/PlanReminderNotification.kt
  app/src/main/res/drawable-hdpi/ic_stat_name.png
  app/src/main/res/drawable-mdpi/ic_stat_name.png
  app/src/main/res/drawable-xhdpi/ic_stat_name.png
  app/src/main/res/drawable-xxhdpi/ic_stat_name.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_name.png
  app/src/main/res/drawable/ic_contact_launcher_background.xml
  app/src/main/res/layout/fragment_notification_time.xml
  app/src/main/res/mipmap-anydpi-v26/ic_contact_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_contact_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_contact_launcher.png
  app/src/main/res/mipmap-hdpi/ic_contact_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_contact_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_contact_launcher.png
  app/src/main/res/mipmap-mdpi/ic_contact_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_contact_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_contact_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_contact_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_contact_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_contact_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_contact_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_contact_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_contact_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_contact_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_contact_launcher_round.png
Labels: chore

#140 그룹명 글자 10자 이하로 제한
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/AddGroupViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature

#142 [FIX] #141 - 위젯 활성화시 약속 데이터 갱신 안되는 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/util/MyRemoteViewsFactory.kt
Labels: bug, 태훈, 🗓️ 일정 기능, fix

#143 [REFACTOR] #129 - 구조변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/service/ContactRemoteViewsFactory.kt
  app/src/main/java/com/ivyclub/contact/service/ContactRemoteViewsService.kt
  app/src/main/java/com/ivyclub/contact/service/WidgetProvider.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/res/drawable/widget_background.xml
  app/src/main/res/layout/item_widget.xml
  app/src/main/res/layout/widget.xml
  app/src/main/res/xml/widget_provider.xml
Labels: 우진, chore

#146 [FIX] 비밀번호 있는 상태에서 푸시 알림을 탭할 때 꺼지는 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
Labels: bug, ❗ 알림 기능, fix, 🔑 보안 기능

#152 연락처 추가 Livedata StateFlow로 변경 외 버그 해결
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/res/drawable/ic_baseline_person_add_24.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: enhancement, 원중, ✈️ 온보딩 기능, 👩‍👩‍👧‍👦 지인 리스트 기능, fix

#169 친구 리스트 버그 수정 및 성능 개선, 앱 세로 고정
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/ImageDetailFragment.kt
  app/src/main/res/layout/fragment_friend.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/ImageManager.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, fix, refactor

#171 친구 추가 시 이미지 저장안되는 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: bug, 우진, ✏️ 지인 추가/수정 기능

#172 패스워드 암호화 및 보안 기능 수정
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/PasswordViewModel.kt
Labels: enhancement, 성희, feature, 🔑 보안 기능

#173 약속 시간 dialog 테마 색상 수정, 알림 시간 변경시 일정 알림 시간 변경
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotification.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/WorkManagerModule.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, ❗ 알림 기능, fix, ui

#175 EditText 이외 다른 View 터치시 키보드 내리기
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
Labels: enhancement, 태훈, feature

#176 Fix/#170 friend detail add
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/anim/enter_anim.xml
  app/src/main/res/anim/exit_anim.xml
  app/src/main/res/anim/pop_enter_anim.xml
  app/src/main/res/anim/pop_exit_anim.xml
  app/src/main/res/drawable/bg_change_image.xml
  app/src/main/res/layout/fragment_add_edit_friend.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/ImageManager.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 우진, 🕵️ 지인 상세 기능, ✏️ 지인 추가/수정 기능

#177 설정 화면 수정 및 그룹 관리 화면 추가
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/GroupListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityViewModel.kt
  app/src/main/res/drawable/bg_switch.xml
  app/src/main/res/drawable/bg_switch_checked.xml
  app/src/main/res/drawable/bg_switch_unchecked.xml
  app/src/main/res/drawable/ic_baseline_groups_24.xml
  app/src/main/res/layout/fragment_dialog_notification_time.xml
  app/src/main/res/layout/fragment_manage_group.xml
  app/src/main/res/layout/fragment_notification_time.xml
  app/src/main/res/layout/fragment_security.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 성희, feature, ⚙️설정화면

#183 친구 리스트 스키마 변경된 부분 반영
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/SelectGroupViewModel.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능

#184 DB 버전 마이그레이션(1 -> 2) 코드 적용
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  data/src/main/java/com/ivyclub/data/DatabaseModule.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDatabase.kt
Labels: 태훈, refactor

#186 온보딩 기능 개선
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/data.json
  app/src/main/java/com/ivyclub/contact/ui/onboard/app_intro/IntroFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/app_intro/ViewPagerAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/ContactAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/splash/SplashActivity.kt
  app/src/main/res/anim/button_down.xml
  app/src/main/res/drawable/intro0.png
  app/src/main/res/drawable/intro1.png
  app/src/main/res/drawable/intro2.png
  app/src/main/res/drawable/intro3.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_add_contact.xml
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_intro.xml
  app/src/main/res/menu/menu_on_boarding_add.xml
  app/src/main/res/navigation/onboarding_nav_graph.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 우진, ✈️ 온보딩 기능, feature

#187 약속 리스트, 상세, 추가/수정 화면 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/res/drawable/ic_check_green.xml
  app/src/main/res/drawable/ic_delete_green.xml
  app/src/main/res/drawable/ic_edit_green.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/values/strings.xml
Labels: 태훈, 🗓️ 일정 기능, ui

#194 그룹 관리 페이지
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/GroupDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/GroupDialogViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/GroupListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupViewModel.kt
  app/src/main/res/layout/dialog_group.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, feature, ⚙️설정화면

#188 친구 상세, 추가/수정 보완
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/res/drawable/ic_baseline_more_vert_24.xml
  app/src/main/res/layout/fragment_add_edit_friend.xml
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/layout/item_add_friend_extra_info.xml
  app/src/main/res/menu/menu_friend_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 성희, feature, 🕵️ 지인 상세 기능, ✏️ 지인 추가/수정 기능

#189 연락처 중복 문제 해결
  app/src/main/java/com/ivyclub/contact/util/ContactListManager.kt
Labels: 원중, fix

#191 기본그룹 생성 중복 오류 & friend 하나도 없을때 사진 저장 오류
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
  app/src/main/res/layout/fragment_add_contact.xml
  app/src/main/res/layout/fragment_intro.xml
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 우진, ✈️ 온보딩 기능, fix, ✏️ 지인 추가/수정 기능

#195 setting화면에서 연락처 추가로 가져오기
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/contact/AddContactFromSettingViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/contact/AddContactFromSettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/contact/NeedPermissionDialog.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/app_intro/IntroFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/dialog/DialogGetContactsLoadingFragment.kt
  app/src/main/java/com/ivyclub/contact/util/SealedClasses.kt
  app/src/main/res/layout/fragment_add_contact.xml
  app/src/main/res/layout/fragment_add_contact_from_settings.xml
  app/src/main/res/layout/fragment_dialog_request_permission.xml
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/fragment_notification_time.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_intro.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 원중, feature, ⚙️설정화면, ui

#196 위젯 리스트 아이템 클릭 기능 추가
  app/src/main/java/com/ivyclub/contact/service/ContactRemoteViewsFactory.kt
  app/src/main/java/com/ivyclub/contact/service/WidgetProvider.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/layout/widget.xml
Labels: enhancement, 태훈, 🗓️ 일정 기능, feature

#203 그룹명 변경 처리
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능

#204 그룹 추가, 변경, 삭제시 스낵바 띄우기
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/dialog/GroupDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/group/ManageGroupFragment.kt
  app/src/main/res/values/strings.xml
Labels: 성희, feature, ⚙️설정화면

#206 알림 설정 앱 꺼지는 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
  data/src/main/java/com/ivyclub/data/MyPreference.kt
Labels: 원중, fix

#209 약속 상세 및 추가/수정 화면 피드백 적용
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan/PlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_close_black.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, 🗓️ 일정 기능, feature, fix, ui

#210 친구 리스트 스크롤바 추가
  app/src/main/res/layout/fragment_friend.xml
Labels: enhancement, 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, ui

#212 [FIX] - 설정 화면에서 알림 시간 설정 완료시 dialog 내리기
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
Labels: feature, fix, ⚙️설정화면

#214 검색창 키보드로 지워서 비워지면 그 자리에 있지 않고 위로 올라가도록 설정
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
Labels: 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, fix

#215 필요없는 의존성 제거 및 테스트 라이브러리 추가
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
Labels: enhancement, 우진

#219 위젯 클릭 관련 버그 수정, 약속 상세 화면 수정
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/layout/fragment_plan_details.xml
  data/build.gradle.kts
Labels: bug, 태훈, fix, ui

#220 지인 상세 정보 화면 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, fix, 🕵️ 지인 상세 기능

#224 롱클릭일 때 롱클릭하면 제대로 처리 되지 않는 버그 해결
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
Labels: 원중, fix

#229 [REFACTOR] bindingAdapter ImageView에서 사용
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_friend_detail.xml
  app/src/main/res/layout/item_friend_profile.xml
Labels: enhancement, 우진

#230 FriendViewModel 테스트 코드 작성
  .github/workflows/develop-branch-review.yml
  app/build.gradle.kts
  app/src/test/java/com/ivyclub/contact/ExampleUnitTest.kt
  app/src/test/java/com/ivyclub/contact/MainCoroutineRule.kt
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  app/src/test/java/com/ivyclub/contact/friendviewmodel/FriendViewModelTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 원중, 👩‍👩‍👧‍👦 지인 리스트 기능, test

#231 패스워드 화면에서 키보드 막기
  app/src/main/java/com/ivyclub/contact/ui/main/settings/security/SecurityFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordViewModel.kt
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/navigation/password_nav_graph.xml
Labels: 성희, fix, 🔑 보안 기능

#221 [FIX] 스플래시 백버튼 누를 때 MainActivity로 이동되는 동작 취소
  app/src/main/java/com/ivyclub/contact/ui/splash/SplashActivity.kt
Labels: bug, 태훈, fix

#232 약속 상세 정보 추가기능 구현
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/ParticipantInfoBottomSheetFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/ParticipantInfoViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/bg_round_bottom_sheet.xml
  app/src/main/res/drawable/ic_baseline_call_24.xml
  app/src/main/res/drawable/ic_send_green.xml
  app/src/main/res/layout/fragment_participant_info.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, 태훈, 🗓️ 일정 기능, feature

#235 친구 추가/수정 ViewModel 테스트코드 작성
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/test/java/com/ivyclub/contact/addeditfriendviewmodel/AddEditFriendViewModelTest.kt
  app/src/test/java/com/ivyclub/contact/addeditfriendviewmodel/InstantTaskExecutorRule.kt
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
Labels: 성희, test, ✏️ 지인 추가/수정 기능

#236 FriendDetailViewModel 테스트
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/test/java/com/ivyclub/contact/InstantTaskExecutorRule.kt
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  app/src/test/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModelTest.kt
Labels: 우진, 🕵️ 지인 상세 기능, test

#237 리드미 작성
  README.md
  docs/ReadMeEn.md
Labels: documentation

#233 약속 notification 수정
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotification.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotificationWorker.kt
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 태훈, feature, ❗ 알림 기능
