Repository boostcampwm-2021/android03-Contact, pull requests merged in 2021-12, with the labels that each got.

#240 [FEAT] #238 - 첫 실행 감지 로직 수정
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
Labels: enhancement, 원중

#242 Work 버전 업데이트 & PlanViewModel 테스트 코드 작성
  app/src/test/java/com/ivyclub/contact/planviewmodel/PlanViewModelTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 태훈, 🗓️ 일정 기능, test

#244 password viewmodel 테스트코드 작성
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/MainViewModel.kt
  app/src/test/java/com/ivyclub/contact/addeditfriendviewmodel/AddEditFriendViewModelTest.kt
  app/src/test/java/com/ivyclub/contact/addeditfriendviewmodel/InstantTaskExecutorRule.kt
  app/src/test/java/com/ivyclub/contact/passwordviewmodel/PasswordViewModelTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 성희, test

#245 온보딩 뷰모델 테스트 코드 작성
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingActivity.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModel.kt
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  app/src/test/java/com/ivyclub/contact/ui/onboard/NotificationTimeViewModelTest.kt
  app/src/test/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModelTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 원중, test

#247 [TEST] assert로 변경
  app/src/test/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModelTest.kt
Labels: 우진, fix

#250 password lock 시점 변경
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
Labels: fix

#253 친구리스트 flow 로직 개선
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendViewModel.kt
Labels: enhancement, refactor

#255 글라이드 캐시 정책 수정
  app/src/main/java/com/ivyclub/contact/util/BindingAdapter.kt
Labels: fix

#259 영어 버전 추가
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
  app/src/main/java/com/ivyclub/contact/util/StringManager.kt
  app/src/main/res/layout/item_plan_list.xml
  app/src/main/res/layout/item_plan_list_header.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/ivyclub/contact/ui/onboard/OnBoardingViewModelTest.kt
Labels: enhancement, 원중

#260 프로젝트 min sdk 추가
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsViewModel.kt
  app/src/test/java/com/ivyclub/contact/ui/onboard/NotificationTimeViewModelTest.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/ivyclub/data/ContactPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
  gradle/common.gradle
Labels: enhancement, 원중, fix

#265 번역되지 않은 string 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/receivers/LanguageChangedReceiver.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/res/layout/fragment_select_group_dialog.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 태훈, fix

#271 약속 사진 id 값 위한 데이터베이스 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  data/src/main/java/com/ivyclub/data/RoomConverters.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
Labels: 원중, feature

#272 약속상세 페이지에 사진추가
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PhotoAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/layout/item_plan_photo.xml
Labels: 우진, 🗓️ 일정 기능, feature

#273 알림 기능 마이그레이션
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ivyclub/contact/MainApplication.kt
  app/src/main/java/com/ivyclub/contact/receivers/AlarmReceiver.kt
  app/src/main/java/com/ivyclub/contact/receivers/BootReceiver.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderMaker.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderMakerImpl.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderMakerModule.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderNotificationWorker.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/WorkManagerModule.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
  app/src/main/res/values-en/strings.xml
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 태훈, ❗ 알림 기능, refactor

#274 비밀번호 횟수 제한
  app/src/main/java/com/ivyclub/contact/service/password_timer/PasswordTimerWorker.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordViewModel.kt
  app/src/main/res/layout/fragment_password.xml
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  data/src/main/java/com/ivyclub/data/ContactPreference.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 🔑 보안 기능

#278 알림 설정 창 개선
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderMaker.kt
  app/src/main/java/com/ivyclub/contact/service/plan_reminder/PlanReminderMakerImpl.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/dialog/NotificationTimeDialogViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/notification/NotificationTimeViewModel.kt
  app/src/main/res/layout/fragment_dialog_notification_time.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  data/src/main/java/com/ivyclub/data/ContactPreference.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement, 태훈, feature, ⚙️설정화면

#277 약속 별로 사진 저장 구현
  app/src/main/java/com/ivyclub/contact/MainApplication.kt
  app/src/main/java/com/ivyclub/contact/customview/CircleXImageView.kt
  app/src/main/java/com/ivyclub/contact/library/image_picker/ImagerPickerFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/AddEditFriendViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_friend/FriendExtraInfoData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/PhotoAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/PhotoData.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/FriendDetailViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/ImageDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/ParticipantInfoViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/BindingExtension.kt
  app/src/main/java/com/ivyclub/contact/util/PixelRatio.kt
  app/src/main/java/com/ivyclub/contact/util/UriToBitmap.kt
  app/src/main/java/com/ivyclub/contact/util/ViewExtension.kt
  app/src/main/res/drawable/ic_baseline_add_24_white.xml
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_image_picker.xml
  app/src/main/res/layout/item_image_at_add_page.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/ivyclub/data/ImageManager.kt
  data/src/main/java/com/ivyclub/data/image/ImageManager.kt
  data/src/main/java/com/ivyclub/data/image/ImageType.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
Labels: enhancement, 원중
