Repository boostcampwm-2021/android03-Contact, pull requests merged in 2022-01, with the labels that each got.

#280 언어 변경 시 약속 리스트 아이템 요일 언어 변경이 되지 않는 이슈
  app/src/main/java/com/ivyclub/contact/service/ContactRemoteViewsFactory.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/plan_list/PlanListItemViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/EnumClasses.kt
Labels: bug, 태훈, fix

#281 Firebase Crashlytics 추가
  .github/workflows/develop-branch-review.yml
  app/build.gradle.kts
  app/services.tar.gpg
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: enhancement, 태훈, chore

#282 시간으로 폴더 생성하던 것 plan id로 변경
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/test/java/com/ivyclub/contact/fake/FakeContactRepository.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/image/ImageManager.kt
  data/src/main/java/com/ivyclub/data/model/ContactData.kt
  data/src/main/java/com/ivyclub/data/repository/ContactDAO.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: enhancement

#286 일정 삭제 시 사진 폴더도 같이 삭제되도록 구현
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  data/src/main/java/com/ivyclub/data/image/ImageManager.kt
Labels: enhancement, 원중, feature

#289 Leak Canary 의존성 추가
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: chore

#291 [FIX] 약속 사진 경로 수정
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PhotoAdapter.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/java/com/ivyclub/contact/util/BindingAdapter.kt
  app/src/main/res/layout/item_plan_photo.xml
Labels: 우진, 🗓️ 일정 기능, fix

#292 비밀번호 확인 화면 버그 수정
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordViewModel.kt
  data/src/main/java/com/ivyclub/data/ContactPreference.kt
  data/src/main/java/com/ivyclub/data/ContactRepository.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: 성희, fix, 🔑 보안 기능

#293 사용한 오픈소스 보여주는 화면 추가
  app/build.gradle.kts
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/res/drawable/ic_baseline_library_books_24.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: 원중, ⚙️설정화면

#300 비밀번호 화면 버그 수정
  app/src/main/java/com/ivyclub/contact/service/password_timer/PasswordTimerWorker.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/password/PasswordViewModel.kt
  data/src/main/java/com/ivyclub/data/ContactPreference.kt
  data/src/main/java/com/ivyclub/data/repository/ContactRepositoryImpl.kt
Labels: bug, 성희, fix, 🔑 보안 기능

#304 기기 재부팅 시 위젯 상태 유지
  app/src/main/java/com/ivyclub/contact/receivers/BootReceiver.kt
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
  app/src/main/java/com/ivyclub/contact/util/BaseFragment.kt
Labels: bug, 태훈, fix

#309 약속 상세화면 UI 수정
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan_details.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 태훈, 🗓️ 일정 기능, ui

#319 약속 추가/수정 화면 초기에 기존 사진 개수 텍스트가 반영되지 않는 문제 해결
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/item_image_at_add_page.xml
Labels: bug, 태훈, 🗓️ 일정 기능, fix, ui

#320 약속 상세 정보 화면 초기에 사진 ViewPager indicator 반영되지 않는 문제 개선
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsFragment.kt
Labels: bug, 태훈, 🗓️ 일정 기능, fix

#322 약속 추가/수정 화면에서 모든 사진 삭제가 반영되지 않는 문제 해결
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanViewModel.kt
Labels: bug, 태훈, 🗓️ 일정 기능, fix

#325 약속 추가/수정 화면 사진 삭제 클릭 delay 해결
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/PhotoAdapter.kt
  app/src/main/java/com/ivyclub/contact/util/FlowExtension.kt
Labels: bug, 태훈, 🗓️ 일정 기능, fix

#326 [REFACTOR] 이미지 라이선스 추가
  app/src/main/java/com/ivyclub/contact/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/license/LicenseFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/license/image_license/ImageLicenseFragment.kt
  app/src/main/res/drawable/ic_baseline_image_24.xml
  app/src/main/res/layout/fragment_image_license.xml
  app/src/main/res/layout/fragment_license.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 우진, chore

#328 [FIX] 오픈소스 라이선스 화면 갔다가 돌아올 때 다시 비밀번호 검사 안하도록 수정
  app/src/main/java/com/ivyclub/contact/ui/main/MainActivity.kt
Labels: bug, 성희, fix
