Repository boostcampwm-2021/android03-Contact, pull requests merged in 2022-05, with the labels that each got.

#346 sms 전송 기능 이슈
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, 태훈, fix

#348 약속 상세 및 수정 화면 제목 text UI 수정
  app/src/main/java/com/ivyclub/contact/ui/main/add_edit_plan/AddEditPlanFragment.kt
  app/src/main/res/layout/fragment_add_edit_plan.xml
  app/src/main/res/layout/fragment_plan_details.xml
Labels: 태훈, 🗓️ 일정 기능, ui

#351 약속 화면 이미지 바인딩 에러 수정
  app/src/main/java/com/ivyclub/contact/ui/main/friend_detail/ImageDetailFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/plan_details/PlanDetailsViewModel.kt
Labels: 원중, fix

#354 flow collect하는 함수 추가
  app/src/main/java/com/ivyclub/contact/ui/main/friend/FriendFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/main/settings/contact/AddContactFromSettingsFragment.kt
  app/src/main/java/com/ivyclub/contact/ui/onboard/contact/AddContactFragment.kt
  app/src/main/java/com/ivyclub/contact/util/FlowExtension.kt
Labels: enhancement, 원중, refactor
